config/routes.rb
Rails.application.routes.draw do

  # /
  root "url_shortners#index"

  resources :url_shortners

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url_shortner.rb
class UrlShortner < ApplicationRecord

  before_save :generate_short_url, :sanitize_data

  def to_param
    self.short_url.to_s
  end


  private
      def generate_short_url
        self.short_url = SecureRandom.urlsafe_base64(3)
      end

      def sanitize_data
        unless self.long_url.include?("https" || "http")
          self.long_url = "https://#{self.long_url}"
        end
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/url_shortners_controller.rb
class UrlShortnersController < ApplicationController

  def index
    @url_shortners = UrlShortner.all
  end

  def show
    @url_shortner = UrlShortner.find_by_short_url(params[:id])
    redirect_to @url_shortner.long_url
  end

  def new
    @url_shortner = UrlShortner.new
  end

  def create
    @url_shortner = UrlShortner.new(url_shortner_params)
    @url_shortner.save!
    redirect_to root_path
  end

  private
    def url_shortner_params
      params.require(:url_shortner).permit(:long_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_shortners_helper.rb
module UrlShortnersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url_shortners/index.html.erb
<body>

<h1 style="text-align:center;">🤯🤯🤯</h1>

<% @url_shortners.each do |us| %>
  <div class="">
    <label for="">Original Url</label>
    <p><%= us.long_url%></p>

    <label for="">Short Url</label>
    <%= link_to us.short_url, us %>
  </div>
  <hr />
<% end %>


<%= link_to "New Shortner", new_url_shortner_path %>

</body>

app/views/url_shortners/new.html.erb
<%= form_for @url_shortner do |form| %>
  <%= form.label(:long_url) %>
  <%= form.text_field :long_url %>


  <%= form.submit %>
<% end %>

app/views/url_shortners/show.html.erb
<h1>UrlShortners#show</h1>
<p>Find me in app/views/url_shortners/show.html.erb</p>